### ISSUE TITLE
Cannot redeclare random_int()

### ISSUE THREAD

**Issue by FatSquirrel93** [paragonie/random_compat#125]
Hey there,

we have just stumbled upon a critical problem. We are using defuse/php-encryption in one of our projects. defuse/php-encryption uses random_compat.

When deploying our project, we receive the following error:
```

PHP error in: xxx/tags/2.0.13/vendor/paragonie/random_compat/lib/random_int.php:

Fatal error: Cannot redeclare random_int() in xxx/tags/2.0.13/vendor/paragonie/random_compat/lib/random_int.php on line 186
Errors parsing xxx/tags/2.0.13/vendor/paragonie/random_compat/lib/random_int.php
```

I have already found the following issue https://github.com/paragonie/random_compat/issues/115 which seems to be talking about a similar problem.

random_int.php does not have an is_callable() check like random_bytes_mcrypt.php.

**Comment by paragonie-scott** [comment]
This is what happens when people include any file *except* `lib/random.php`, against our recommendation. The usual fix is "don't do that, use random.php instead", but in this case I think the culprit is box.json.

https://github.com/paragonie/random_compat/commit/13004a71bc278712129a882c864f8706fb781049?w=1 will fix it. I'll get a new release out ASAP, and will bug @defuse to see if he needs to release a new .phar.
