### ISSUE TITLE
v2.99.99 shouldnt it be v2.0.13?

### ISSUE THREAD

**Issue by TerraSkye** [paragonie/random_compat#140]
the jump is kinda high

**Comment by pxgamer** [comment]
I think this is solely for PHP `^7` projects, where the `random_compat` library isn't necessary.

v2.0.13 seems to also have been created which covers PHP `>=5.2.0` as before.

**Comment by paragonie-scott** [comment]
@pxgamer is correct.

https://github.com/paragonie/random_compat/releases/tag/v2.0.13

https://github.com/paragonie/random_compat/blob/v2.99.99/CHANGELOG.md

**Comment by GrahamCampbell** [comment]
I think that's the wrong solution tbh.

A better solution is for an application to do something like this:

```json
    "replace": {
        "paragonie/random_compat": "*",
        "symfony/polyfill-php56": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-mbstring": "*"
    },
```

**Comment by paragonie-scott** [comment]
If you're never going to run on PHP 5 (i.e. you're using a library that is compatible with PHP 5 but your software is only PHP 7), you can continue using `"^2"` as your require string for random_compat.

Otherwise, if you explicitly need PHP 5 support (which will become an increasingly bad idea, as it's approaching EOL in 6 months), `">=2.0 <2.99"` does the trick.

Nobody should be using v1 of this library anymore. OpenSSL's RNG needs to die.

**Comment by is06** [comment]
Symfony 2.8 still require the random_compat with this require section:

"require": {
    "paragonie/random_compat": "~1.0|~2.0",
    "php": ">=5.3.3"
},

So why did you break compatibility in v2 ? Semver is not such a bad idea...

**Comment by paragonie-scott** [comment]
> So why did you break compatibility in v2 ? Semver is not such a bad idea...

Okay, fuck it, I'll delete the tag.

**Comment by paragonie-scott** [comment]
Tag is deleted.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/random_compat/commit/24729dbcb132c6a80b7a0d8a4824ffca4bc1d3bc

Updated README to allow people who don't need PHP 5 support to be able to easily support the NOP version of this library.
